# Generated by Django 4.2.3 on 2024-10-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialVideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialvideo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='posts/images'),
        ),
        migrations.AlterField(
            model_name='socialvideo',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
